version: 2
jobs:
  build:
    branches:
      only:
        - master
    resource_class: xlarge
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PWD
            cd /root/project/docker && sh ./build.sh