version: 2
jobs:
  build:
    branches:
      only:
        - master
    resource_class: xlarge
    docker:
          # specify the version you desire here
          # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
          - image: circleci/python:3.6.1

          # Specify service dependencies here if necessary
          # CircleCI maintains a library of pre-built images
          # documented at https://circleci.com/docs/2.0/circleci-images/
          # - image: circleci/postgres:9.4

    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PWD
            cd ~/repo/docker && sh ./build.sh