version: '2'
services:
    influxdb-tools:
        image: "gubinempower/influxdb-tools"
        volumes:
            - /data/influxdbbackup:/var/lib/influxdb
        restart: "always"
        environment:
            - HOST=127.0.0.1
            - PORT=8088
            - DATABASE=empoweriot
            - DIR=/var/lib/influxdb/backup
            - INTERVAL=86400
