version: '2'
services:
    influxdb-tools:
        image: "gubinempower/influxdb-tools"
        volumes:
            - /data/influxdbbackup:/var/lib/influxdb
        restart: "always"
        environment:
            - HOST=192.168.1.12
            - PORT=8088
            - DATABASE=empoweriot
            - DIR=/var/lib/influxdb/backup
            - INTERVAL=5
